stages:
  - publish

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public

pages:
  stage: publish
  job1:
      script:
      - mkdir .public
      - mkdir -p public/$CI_COMMIT_REF_NAME/
      - cp -r docs/. public/$CI_COMMIT_REF_NAME/
      - mv .public public/$CI_COMMIT_REF_NAME/
      artifacts:
        name: "$CI_COMMIT_REF_NAME"
        paths:
        - public
        expire_in: 5 days
      when: always
      except:
      - master

  job2:
      script:
      - mkdir .public
      - mkdir -p public/$CI_COMMIT_REF_NAME/
      - cp -r docs/. public/$CI_COMMIT_REF_NAME/
      - mv .public public/$CI_COMMIT_REF_NAME/
      artifacts:
        name: "$CI_COMMIT_REF_NAME"
        paths:
        - public
      only:
      - master